package fun.greenplay.app;
import android.app.*;import android.content.*;import android.os.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;import javax.crypto.Cipher;import javax.crypto.spec.IvParameterSpec;import javax.crypto.spec.SecretKeySpec;

public class OfflineDownloadService extends Service{
 public static final String ACTION_START="fun.greenplay.app.OFFLINE_START",ACTION_CANCEL="fun.greenplay.app.OFFLINE_CANCEL";
 static final String CHANNEL="greenplay_offline";static final Set<String> cancelled=Collections.newSetFromMap(new ConcurrentHashMap<String,Boolean>());static final ExecutorService pool=Executors.newSingleThreadExecutor();android.content.SharedPreferences sp;
 static final String UA="Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 Chrome/120 Mobile Safari/537.36";
 public void onCreate(){super.onCreate();sp=getSharedPreferences("gp",0);createChannel();}
 public int onStartCommand(Intent in,int flags,int startId){if(in==null){stopSelf(startId);return START_NOT_STICKY;}String action=in.getAction();if(ACTION_CANCEL.equals(action)){String cid=in.getStringExtra("content_id");if(cid!=null)cancelled.add(cid);String path=in.getStringExtra("path");if(path!=null){new File(path).delete();new File(path+".part").delete();}stopSelf(startId);return START_NOT_STICKY;}if(!ACTION_START.equals(action)){stopSelf(startId);return START_NOT_STICKY;}String cid=in.getStringExtra("content_id"),title=in.getStringExtra("title"),url=in.getStringExtra("url"),urls=in.getStringExtra("urls"),path=in.getStringExtra("path");startForeground(notificationId(cid),notification(title,0,false));cancelled.remove(cid);pool.execute(()->download(cid,title,url,urls,path,startId));return START_NOT_STICKY;}

 void download(String cid,String title,String primary,String urlsJson,String path,int startId){File part=new File(path+".part"),dest=new File(path);Exception last=null;try{File parent=dest.getParentFile();if(parent!=null&&!parent.exists()&&!parent.mkdirs())throw new IOException("Pasta indisponível");ArrayList<String> urls=candidateUrls(primary,urlsJson);if(urls.isEmpty())throw new IOException("URL vazia");update(cid,"downloading",0,0,null);for(String url:urls){for(int attempt=0;attempt<2;attempt++){checkCancelled(cid);part.delete();try{downloadOne(cid,title,url,part);finishFile(cid,title,part,dest);return;}catch(InterruptedIOException e){part.delete();return;}catch(Exception e){last=e;part.delete();sleepBackoff(attempt);}}}throw last==null?new IOException("Falha no download"):last;}catch(InterruptedIOException e){part.delete();}catch(Exception e){part.delete();if(!cancelled.remove(cid))update(cid,"failed",0,0,safeError(e));}finally{stopForeground(true);stopSelf(startId);}}
 ArrayList<String> candidateUrls(String primary,String json){LinkedHashSet<String> out=new LinkedHashSet<>();if(primary!=null&&!primary.trim().isEmpty())out.add(primary.trim());try{JSONArray a=new JSONArray(json==null?"[]":json);for(int i=0;i<a.length();i++){String u=a.optString(i,"").trim();if(!u.isEmpty())out.add(u);}}catch(Exception ignored){}return new ArrayList<>(out);}
 void finishFile(String cid,String title,File part,File dest)throws Exception{checkCancelled(cid);if(!part.exists()||part.length()<64*1024)throw new IOException("Arquivo incompleto");if(dest.exists())dest.delete();if(!part.renameTo(dest)){copy(part,dest);part.delete();}update(cid,"ready",dest.length(),dest.length(),null);updateNotification(cid,title,dest.length(),dest.length(),true);}
 void downloadOne(String cid,String title,String url,File part)throws Exception{if(url==null||url.trim().isEmpty())throw new IOException("URL vazia");boolean hls=isLikelyHls(url);if(!hls){HttpURLConnection c=open(url,null);BufferedInputStream in=null;try{String ct=lower(c.getContentType());in=new BufferedInputStream(c.getInputStream());in.mark(16384);byte[] probe=new byte[8192];int pn=in.read(probe);in.reset();String head=pn>0?new String(probe,0,pn,StandardCharsets.UTF_8).trim():"";if(ct.contains("mpegurl")||head.startsWith("#EXTM3U")){hls=true;}else{if(ct.contains("text/html")||ct.contains("application/json")||head.startsWith("<!DOCTYPE")||head.startsWith("<html")||head.startsWith("{"))throw new IOException("Resposta inválida");long total=contentLength(c);writeDirect(cid,title,in,new FileOutputStream(part),total);in=null;}}finally{if(in!=null)try{in.close();}catch(Exception ignored){}c.disconnect();}}if(hls){part.delete();downloadHls(cid,title,url,part,0);}}
 boolean isLikelyHls(String u){String x=lower(u);return x.contains(".m3u8")||x.contains("format=m3u8")||x.contains("type=hls");}
 HttpURLConnection open(String url,String range)throws IOException{IOException first=null;try{return openPolicy(url,range,true);}catch(IOException e){first=e;String m=e.getMessage()==null?"":e.getMessage();if(!(m.contains("HTTP 401")||m.contains("HTTP 403")||m.contains("HTTP 406")||m.contains("HTTP 429")))throw e;}try{return openPolicy(url,range,false);}catch(IOException e){throw first==null?e:first;}}
 HttpURLConnection openPolicy(String initial,String range,boolean webHeaders)throws IOException{String current=initial;for(int redirects=0;redirects<8;redirects++){URL u=new URL(current);HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setConnectTimeout(20000);c.setReadTimeout(60000);c.setInstanceFollowRedirects(false);c.setRequestProperty("User-Agent",UA);c.setRequestProperty("Accept","*/*");c.setRequestProperty("Accept-Encoding","identity");c.setRequestProperty("Connection","keep-alive");if(webHeaders){c.setRequestProperty("Referer","https://greenplay.fun/");c.setRequestProperty("Origin","https://greenplay.fun");}if(range!=null&&!range.isEmpty())c.setRequestProperty("Range",range);int code=c.getResponseCode();if(code>=300&&code<400){String loc=c.getHeaderField("Location");c.disconnect();if(loc==null||loc.trim().isEmpty())throw new IOException("Redirecionamento inválido");current=new URL(u,loc).toString();continue;}if(code<200||code>=400){c.disconnect();throw new IOException("HTTP "+code);}return c;}throw new IOException("Redirecionamentos demais");}
 long contentLength(HttpURLConnection c){try{return Build.VERSION.SDK_INT>=24?c.getContentLengthLong():c.getContentLength();}catch(Exception e){return -1;}}
 String lower(String s){return s==null?"":s.toLowerCase(Locale.ROOT);}
 String safeError(Exception e){String m=e==null?"":e.getMessage();if(m==null||m.trim().isEmpty())return "Falha no download";if(m.length()>100)m=m.substring(0,100);return m;}
 void sleepBackoff(int attempt){try{Thread.sleep(attempt==0?650:1300);}catch(Exception ignored){}}

 void writeDirect(String cid,String title,InputStream in,OutputStream raw,long total)throws IOException{try(InputStream input=in;OutputStream out=new BufferedOutputStream(raw)){byte[] buf=new byte[128*1024];long done=0,last=0;int n;while((n=input.read(buf))!=-1){checkCancelled(cid);out.write(buf,0,n);done+=n;long now=System.currentTimeMillis();if(now-last>700){update(cid,"downloading",done,total,null);updateNotification(cid,title,done,total,false);last=now;}}out.flush();update(cid,"downloading",done,total,null);}}

 void downloadHls(String cid,String title,String initialUrl,File part,int depth)throws Exception{if(depth>4)throw new IOException("Playlist inválida");String text=downloadTextRetry(initialUrl);if(!text.trim().startsWith("#EXTM3U"))throw new IOException("Playlist inválida");String[] lines=text.replace("\r","").split("\n");ArrayList<Variant> vars=parseVariants(initialUrl,lines);if(!vars.isEmpty()){Collections.sort(vars,(a,b)->Long.compare(b.bandwidth,a.bandwidth));Exception last=null;for(Variant v:vars){part.delete();try{downloadHls(cid,title,v.url,part,depth+1);return;}catch(InterruptedIOException e){throw e;}catch(Exception e){last=e;}}throw last==null?new IOException("Nenhuma qualidade disponível"):last;}Playlist pl=parseMedia(initialUrl,lines);downloadMediaPlaylist(cid,title,pl,part);}
 ArrayList<Variant> parseVariants(String base,String[] lines)throws Exception{ArrayList<Variant> vars=new ArrayList<>();for(int i=0;i<lines.length;i++){String l=lines[i].trim();if(l.startsWith("#EXT-X-STREAM-INF:")){long bw=parseLongAttr(l,"BANDWIDTH");String next=nextUri(lines,i+1);if(next!=null)vars.add(new Variant(resolve(base,next),bw));}}return vars;}
 void downloadMediaPlaylist(String cid,String title,Playlist pl,File part)throws Exception{if(pl.segments.isEmpty())throw new IOException("Playlist sem segmentos");long estimated=pl.totalBytes,done=0,last=0;try(OutputStream out=new BufferedOutputStream(new FileOutputStream(part))){if(pl.map!=null){byte[] init=downloadBytesRetry(pl.map.url,pl.map.range);if(pl.map.key!=null)init=decrypt(init,pl.map.key,pl.map.sequence);out.write(init);done+=init.length;}for(Segment s:pl.segments){checkCancelled(cid);byte[] data=downloadBytesRetry(s.url,s.range);if(s.key!=null)data=decrypt(data,s.key,s.sequence);out.write(data);done+=data.length;long now=System.currentTimeMillis();if(now-last>500){update(cid,"downloading",done,estimated,null);updateNotification(cid,title,done,estimated,false);last=now;}}out.flush();update(cid,"downloading",done,done,null);}}
 Playlist parseMedia(String base,String[] lines)throws Exception{Playlist p=new Playlist();long mediaSeq=0;KeyInfo key=null;ByteRange pendingRange=null;long rangeOffset=0;for(int i=0;i<lines.length;i++){String l=lines[i].trim();if(l.isEmpty())continue;if(l.startsWith("#EXT-X-MEDIA-SEQUENCE:")){try{mediaSeq=Long.parseLong(l.substring(l.indexOf(':')+1).trim());}catch(Exception ignored){}}else if(l.startsWith("#EXT-X-KEY:")){String method=attr(l,"METHOD");if("NONE".equalsIgnoreCase(method)){key=null;}else if("AES-128".equalsIgnoreCase(method)){String uri=attr(l,"URI"),iv=attr(l,"IV");key=new KeyInfo(resolve(base,stripQuotes(uri)),iv);}else throw new IOException("Criptografia HLS não suportada");}else if(l.startsWith("#EXT-X-BYTERANGE:")){String raw=l.substring(l.indexOf(':')+1).trim();String[] z=raw.split("@");long len=Long.parseLong(z[0]);if(z.length>1)rangeOffset=Long.parseLong(z[1]);pendingRange=new ByteRange(rangeOffset,len);rangeOffset+=len;}else if(l.startsWith("#EXT-X-MAP:")){String uri=stripQuotes(attr(l,"URI"));String br=attr(l,"BYTERANGE");ByteRange rr=parseByteRange(br,0);p.map=new Segment(resolve(base,uri),rr,key,mediaSeq);}else if(!l.startsWith("#")){p.segments.add(new Segment(resolve(base,l),pendingRange,key,mediaSeq+p.segments.size()));pendingRange=null;}}return p;}
 String nextUri(String[] lines,int start){for(int i=start;i<lines.length;i++){String x=lines[i].trim();if(x.isEmpty()||x.startsWith("#"))continue;return x;}return null;}
 long parseLongAttr(String l,String name){try{return Long.parseLong(attr(l,name));}catch(Exception e){return 0;}}
 String attr(String line,String name){int c=line.indexOf(':');String s=c>=0?line.substring(c+1):line;boolean q=false;StringBuilder cur=new StringBuilder();ArrayList<String> parts=new ArrayList<>();for(int i=0;i<s.length();i++){char ch=s.charAt(i);if(ch=='\"')q=!q;if(ch==','&&!q){parts.add(cur.toString());cur.setLength(0);}else cur.append(ch);}parts.add(cur.toString());for(String part:parts){int eq=part.indexOf('=');if(eq>0&&part.substring(0,eq).trim().equalsIgnoreCase(name))return part.substring(eq+1).trim();}return "";}
 String stripQuotes(String s){if(s==null)return "";s=s.trim();if(s.length()>=2&&s.startsWith("\"")&&s.endsWith("\""))return s.substring(1,s.length()-1);return s;}
 ByteRange parseByteRange(String raw,long fallback){if(raw==null||raw.isEmpty())return null;raw=stripQuotes(raw);try{String[] z=raw.split("@");long len=Long.parseLong(z[0]),off=z.length>1?Long.parseLong(z[1]):fallback;return new ByteRange(off,len);}catch(Exception e){return null;}}
 String resolve(String base,String rel)throws MalformedURLException{return new URL(new URL(base),rel).toString();}
 String downloadTextRetry(String url)throws IOException{IOException last=null;for(int i=0;i<3;i++){try{return downloadText(url);}catch(IOException e){last=e;sleepBackoff(i);}}throw last==null?new IOException("Falha na playlist"):last;}
 String downloadText(String url)throws IOException{HttpURLConnection c=open(url,null);try(InputStream in=c.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[32768];int n;while((n=in.read(b))>0){if(out.size()>4*1024*1024)throw new IOException("Playlist muito grande");out.write(b,0,n);}return out.toString("UTF-8");}finally{c.disconnect();}}
 byte[] downloadBytesRetry(String url,ByteRange r)throws IOException{IOException last=null;for(int i=0;i<3;i++){try{return downloadBytes(url,r);}catch(IOException e){last=e;sleepBackoff(i);}}throw last==null?new IOException("Falha em segmento"):last;}
 byte[] downloadBytes(String url,ByteRange r)throws IOException{String range=r==null?null:"bytes="+r.offset+"-"+(r.offset+r.length-1);HttpURLConnection c=open(url,range);try(InputStream raw=new BufferedInputStream(c.getInputStream());ByteArrayOutputStream out=new ByteArrayOutputStream(r!=null?(int)Math.min(Integer.MAX_VALUE,r.length):128*1024)){InputStream in=raw;long remain=r==null?Long.MAX_VALUE:r.length;if(r!=null&&c.getResponseCode()==200&&r.offset>0){long skip=r.offset;while(skip>0){long n=in.skip(skip);if(n<=0){if(in.read()==-1)throw new EOFException("Faixa inválida");n=1;}skip-=n;}}byte[] b=new byte[128*1024];while(remain>0){int want=(int)Math.min(b.length,remain),n=in.read(b,0,want);if(n<0)break;out.write(b,0,n);if(r!=null)remain-=n;}return out.toByteArray();}finally{c.disconnect();}}
 byte[] decrypt(byte[] data,KeyInfo k,long sequence)throws Exception{if(k==null)return data;byte[] key=downloadBytesRetry(k.uri,null);if(key.length<16)throw new IOException("Chave HLS inválida");key=Arrays.copyOf(key,16);byte[] iv=parseIv(k.iv,sequence);Cipher cp=Cipher.getInstance("AES/CBC/PKCS5Padding");cp.init(Cipher.DECRYPT_MODE,new SecretKeySpec(key,"AES"),new IvParameterSpec(iv));return cp.doFinal(data);}
 byte[] parseIv(String raw,long seq){byte[] iv=new byte[16];if(raw!=null&&!raw.isEmpty()){String h=raw.toLowerCase(Locale.ROOT).replace("0x","").replaceAll("[^0-9a-f]","");while(h.length()<32)h="0"+h;if(h.length()>32)h=h.substring(h.length()-32);for(int i=0;i<16;i++)try{iv[i]=(byte)Integer.parseInt(h.substring(i*2,i*2+2),16);}catch(Exception ignored){}return iv;}for(int i=15;i>=0&&seq!=0;i--){iv[i]=(byte)(seq&0xff);seq>>>=8;}return iv;}
 void checkCancelled(String cid)throws InterruptedIOException{if(cancelled.contains(cid))throw new InterruptedIOException("cancelled");}
 void copy(File a,File b)throws IOException{try(InputStream in=new FileInputStream(a);OutputStream out=new FileOutputStream(b)){byte[] x=new byte[65536];int n;while((n=in.read(x))>0)out.write(x,0,n);}}
 synchronized void update(String cid,String status,long done,long total,String error){try{JSONArray a=new JSONArray(sp.getString("offline_items","[]"));for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&cid.equals(o.optString("content_id"))){o.put("status",status);o.put("downloaded",done);if(total>0)o.put("total",total);if(error!=null)o.put("error",error);else o.remove("error");sp.edit().putString("offline_items",a.toString()).apply();return;}}}catch(Exception ignored){}}
 void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel ch=new NotificationChannel(CHANNEL,"Downloads",NotificationManager.IMPORTANCE_LOW);ch.setDescription("Downloads do GreenPlay");((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(ch);}}
 Notification notification(String title,int progress,boolean done){Intent open=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,0,open,Build.VERSION.SDK_INT>=23?PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT:PendingIntent.FLAG_UPDATE_CURRENT);Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CHANNEL):new Notification.Builder(this);b.setSmallIcon(done?android.R.drawable.stat_sys_download_done:android.R.drawable.stat_sys_download).setContentTitle(title==null?"GreenPlay":title).setContentText(done?"Pronto para assistir":"Baixando").setContentIntent(pi).setOnlyAlertOnce(true).setOngoing(!done);if(!done)b.setProgress(100,Math.max(0,progress),progress<=0);return b.build();}
 void updateNotification(String cid,String title,long done,long total,boolean forceDone){int p=total>0?(int)Math.min(100,done*100/total):0;((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(notificationId(cid),notification(title,p,forceDone||(total>0&&done>=total)));}
 int notificationId(String cid){return 2200+Math.abs((cid==null?"0":cid).hashCode()%5000);}
 public android.os.IBinder onBind(Intent i){return null;}
 static class ByteRange{long offset,length;ByteRange(long o,long l){offset=o;length=l;}}
 static class KeyInfo{String uri,iv;KeyInfo(String u,String i){uri=u;iv=i;}}
 static class Segment{String url;ByteRange range;KeyInfo key;long sequence;Segment(String u,ByteRange r,KeyInfo k,long s){url=u;range=r;key=k;sequence=s;}}
 static class Variant{String url;long bandwidth;Variant(String u,long b){url=u;bandwidth=b;}}
 static class Playlist{ArrayList<Segment> segments=new ArrayList<>();Segment map;long totalBytes=0;}
}
