package fun.greenplay.app;

import android.app.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import android.net.*;
import android.graphics.Color;
import android.content.*;
import android.content.pm.ActivityInfo;
import android.graphics.drawable.GradientDrawable;
import java.util.*;

import androidx.media3.common.C;
import androidx.media3.common.MediaItem;
import androidx.media3.common.PlaybackException;
import androidx.media3.common.Player;
import androidx.media3.datasource.DefaultDataSource;
import androidx.media3.datasource.DefaultHttpDataSource;
import androidx.media3.exoplayer.ExoPlayer;
import androidx.media3.exoplayer.DefaultLoadControl;
import androidx.media3.exoplayer.source.DefaultMediaSourceFactory;
import androidx.media3.ui.AspectRatioFrameLayout;
import androidx.media3.ui.PlayerView;

public class PlayerActivity extends Activity{
 static final ArrayList<HashMap<String,String>> EPISODE_QUEUE=new ArrayList<>(); static int EPISODE_INDEX=-1;
 public static synchronized void setEpisodeQueue(ArrayList<HashMap<String,String>> q,int index){EPISODE_QUEUE.clear();if(q!=null)EPISODE_QUEUE.addAll(q);EPISODE_INDEX=index;}
 PlayerView playerView; ExoPlayer player; FrameLayout frame; LinearLayout controls; SeekBar seek; TextView time,play,displayModeButton; Handler h=new Handler(Looper.getMainLooper()); boolean live=false,prepared=false,switching=false,tickerStarted=false,episodeQueue=false,tvMode=false,resumeAfterBackground=false,seekingTouch=false; int sourceIndex=0,pendingSeek=0,bufferStarts=0,episodeIndex=-1,displayMode=0,pendingSeekProgress=-1; long lastBufferAt=0; final ArrayList<String> sources=new ArrayList<>();
 int green=Color.rgb(32,224,112); String seriesId="",episodeId="",episodeTitle="",seasonNumber="",episodeNumber="",movieId="",movieTitle="",moviePoster="",movieLandscape="",gpUserId="",gpDeviceId=""; long lastProgressSave=0; Runnable sessionBeat;
 public void onCreate(Bundle b){super.onCreate(b);tvMode=DeviceCompat.isTelevisionDevice(this);setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE);getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);applyImmersive();live=getIntent().getBooleanExtra("live",false);episodeQueue=getIntent().getBooleanExtra("episode_queue",false);episodeIndex=getIntent().getIntExtra("episode_index",EPISODE_INDEX);seriesId=nz(getIntent().getStringExtra("series_id"));episodeId=nz(getIntent().getStringExtra("episode_id"));episodeTitle=nz(getIntent().getStringExtra("episode_title"));seasonNumber=nz(getIntent().getStringExtra("season_number"));episodeNumber=nz(getIntent().getStringExtra("episode_number"));movieId=nz(getIntent().getStringExtra("movie_id"));movieTitle=nz(getIntent().getStringExtra("movie_title"));moviePoster=nz(getIntent().getStringExtra("movie_poster"));movieLandscape=nz(getIntent().getStringExtra("movie_landscape"));gpUserId=nz(getIntent().getStringExtra("gp_user_id"));gpDeviceId=nz(getIntent().getStringExtra("gp_device_id"));pendingSeek=Math.max(0,getIntent().getIntExtra("resume_ms",0));if(episodeQueue&&episodeIndex>=0){EPISODE_INDEX=episodeIndex;applyEpisodeMetadata();}build();startSessionHeartbeat();open();}
 String nz(String v){return v==null?"":v;}
 void applyImmersive(){try{getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY|View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN|View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_LAYOUT_STABLE);}catch(Exception ignored){}}
 @Override public void onWindowFocusChanged(boolean hasFocus){super.onWindowFocusChanged(hasFocus);if(hasFocus)applyImmersive();}
 void startSessionHeartbeat(){if(gpUserId.isEmpty()||gpDeviceId.isEmpty())return;sessionBeat=new Runnable(){public void run(){if(isFinishing())return;Api.post("stream_session",Api.m("user_id",gpUserId,"device_id",gpDeviceId,"action","heartbeat"),new Api.CB(){public void ok(org.json.JSONObject j){}public void err(String e){}});h.postDelayed(this,45000);}};h.postDelayed(sessionBeat,45000);}
 void releaseStreamSession(){if(gpUserId.isEmpty()||gpDeviceId.isEmpty())return;Api.post("stream_session",Api.m("user_id",gpUserId,"device_id",gpDeviceId,"action","release"),new Api.CB(){public void ok(org.json.JSONObject j){}public void err(String e){}});}
 int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 TextView tx(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextColor(Color.WHITE);t.setTextSize(size);t.setGravity(Gravity.CENTER);return t;}
 int tvFocusId(View v){if(v==null)return View.NO_ID;if(v.getId()==View.NO_ID)v.setId(View.generateViewId());return v.getId();}
 void tvLinkH(View left,View right){if(!tvMode||left==null||right==null)return;int a=tvFocusId(left),b=tvFocusId(right);left.setNextFocusRightId(b);right.setNextFocusLeftId(a);}
 void tvLinkV(View up,View down){if(!tvMode||up==null||down==null)return;int a=tvFocusId(up),b=tvFocusId(down);up.setNextFocusDownId(b);down.setNextFocusUpId(a);}
 void tvControl(View v){if(!tvMode||v==null)return;v.setFocusable(true);v.setFocusableInTouchMode(true);v.setOnFocusChangeListener((x,has)->{x.animate().scaleX(1f).scaleY(1f).setDuration(0).start();if(android.os.Build.VERSION.SDK_INT>=21)x.setTranslationZ(has?dp(8):0);});}
 long durationMs(){try{if(player==null)return 0;long d=player.getDuration();return d==C.TIME_UNSET||d<0?0:d;}catch(Exception e){return 0;}}
 long positionMs(){try{return player==null?0:Math.max(0,player.getCurrentPosition());}catch(Exception e){return 0;}}
 void togglePlayback(){if(!prepared||player==null)return;if(player.isPlaying()){player.pause();play.setText("▶");}else{player.play();play.setText("Ⅱ");}}
 void seekBy(long ms){if(live||!prepared||player==null)return;long d=durationMs(),target=Math.max(0,positionMs()+ms);if(d>0)target=Math.min(Math.max(0,d-250),target);player.seekTo(target);updateProgressNow();}
 void seekFraction(int progress){if(live||!prepared||player==null)return;long d=durationMs();if(d<=0)return;long target=(long)(d*(Math.max(0,Math.min(1000,progress))/1000d));if(target>=d)target=Math.max(0,d-50);player.seekTo(target);updateProgressNow();}
 void applyDisplayMode(){if(playerView==null)return;if(displayMode==1)playerView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_ZOOM);else if(displayMode==2)playerView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_FILL);else playerView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_FIT);if(displayModeButton!=null)displayModeButton.setText(displayMode==1?"▣ Zoom":displayMode==2?"▣ Preencher":"▣ Ajustar");getSharedPreferences("gp",0).edit().putInt("player_display_mode",displayMode).apply();}
 void cycleDisplayMode(){displayMode=(displayMode+1)%3;applyDisplayMode();}
 void build(){frame=new FrameLayout(this);frame.setBackgroundColor(Color.BLACK);
  displayMode=getSharedPreferences("gp",0).getInt("player_display_mode",0);if(displayMode<0||displayMode>2)displayMode=0;playerView=new PlayerView(this);playerView.setUseController(false);playerView.setShutterBackgroundColor(Color.BLACK);FrameLayout.LayoutParams vp=new FrameLayout.LayoutParams(-1,-1,Gravity.CENTER);frame.addView(playerView,vp);
  HashMap<String,String> requestHeaders=new HashMap<>();requestHeaders.put("Referer","https://greenplay.fun/");requestHeaders.put("Origin","https://greenplay.fun");DefaultHttpDataSource.Factory httpFactory=new DefaultHttpDataSource.Factory().setUserAgent("Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 Chrome/120 Mobile Safari/537.36").setAllowCrossProtocolRedirects(true).setConnectTimeoutMs(8000).setReadTimeoutMs(18000).setDefaultRequestProperties(requestHeaders);DefaultDataSource.Factory dataFactory=new DefaultDataSource.Factory(this,httpFactory);DefaultLoadControl loadControl=new DefaultLoadControl.Builder().setBufferDurationsMs(1200,30000,350,700).setPrioritizeTimeOverSizeThresholds(true).build();player=new ExoPlayer.Builder(this).setLoadControl(loadControl).setMediaSourceFactory(new DefaultMediaSourceFactory(dataFactory)).build();playerView.setPlayer(player);
  TextView back=tx("‹",34);back.setBackground(bg(0x77000000,24));back.setOnClickListener(v->finish());FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(dp(48),dp(48),Gravity.TOP|Gravity.LEFT);bp.setMargins(dp(14),dp(14),0,0);frame.addView(back,bp);
  controls=new LinearLayout(this);controls.setOrientation(LinearLayout.VERTICAL);controls.setPadding(dp(18),dp(10),dp(18),dp(10));controls.setBackgroundColor(0xaa000000);
  LinearLayout buttons=new LinearLayout(this);buttons.setGravity(Gravity.CENTER);TextView back10=tx("↶ 10",18);play=tx("Ⅱ",28);TextView fwd10=tx("10 ↷",18);displayModeButton=tx("▣ Ajustar",16);buttons.addView(back10,new LinearLayout.LayoutParams(dp(105),dp(52)));buttons.addView(play,new LinearLayout.LayoutParams(dp(80),dp(52)));buttons.addView(fwd10,new LinearLayout.LayoutParams(dp(105),dp(52)));buttons.addView(displayModeButton,new LinearLayout.LayoutParams(dp(132),dp(52)));controls.addView(buttons,new LinearLayout.LayoutParams(-1,dp(54)));
  LinearLayout progress=new LinearLayout(this);progress.setGravity(Gravity.CENTER_VERTICAL);time=tx("00:00",13);time.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);progress.addView(time,new LinearLayout.LayoutParams(dp(112),dp(36)));seek=new SeekBar(this);seek.setMax(1000);seek.setProgressTintList(android.content.res.ColorStateList.valueOf(green));seek.setThumbTintList(android.content.res.ColorStateList.valueOf(green));progress.addView(seek,new LinearLayout.LayoutParams(0,dp(36),1));controls.addView(progress,new LinearLayout.LayoutParams(-1,dp(38)));FrameLayout.LayoutParams cp=new FrameLayout.LayoutParams(-1,dp(104),Gravity.BOTTOM|Gravity.CENTER_HORIZONTAL);cp.setMargins(dp(28),0,dp(28),dp(18));frame.addView(controls,cp);
  applyDisplayMode();back10.setOnClickListener(v->seekBy(-10000));fwd10.setOnClickListener(v->seekBy(10000));play.setOnClickListener(v->togglePlayback());displayModeButton.setOnClickListener(v->cycleDisplayMode());if(tvMode){tvControl(back);tvControl(back10);tvControl(play);tvControl(fwd10);tvControl(displayModeButton);tvControl(seek);tvLinkH(back10,play);tvLinkH(play,fwd10);tvLinkH(fwd10,displayModeButton);tvLinkV(play,seek);tvLinkV(displayModeButton,seek);tvLinkV(back,play);play.postDelayed(()->play.requestFocus(),180);}seek.setEnabled(!live);seek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean from){if(from&&!live){pendingSeekProgress=p;long d=durationMs();if(d>0)time.setText(fmt((long)(d*(Math.max(0,Math.min(1000,p))/1000d)))+" / "+fmt(d));}}public void onStartTrackingTouch(SeekBar s){seekingTouch=true;pendingSeekProgress=s.getProgress();}public void onStopTrackingTouch(SeekBar s){seekingTouch=false;if(pendingSeekProgress>=0)seekFraction(pendingSeekProgress);pendingSeekProgress=-1;updateProgressNow();}});frame.setOnClickListener(v->{controls.setVisibility(controls.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE);});setContentView(frame);
 }
 @Override public boolean dispatchKeyEvent(KeyEvent e){if(tvMode&&e!=null&&e.getAction()==KeyEvent.ACTION_DOWN){int k=e.getKeyCode();if(controls!=null&&controls.getVisibility()!=View.VISIBLE&&(k==KeyEvent.KEYCODE_DPAD_UP||k==KeyEvent.KEYCODE_DPAD_DOWN||k==KeyEvent.KEYCODE_DPAD_LEFT||k==KeyEvent.KEYCODE_DPAD_RIGHT||k==KeyEvent.KEYCODE_DPAD_CENTER||k==KeyEvent.KEYCODE_ENTER)){controls.setVisibility(View.VISIBLE);if(play!=null)play.requestFocus();return true;}if(k==KeyEvent.KEYCODE_MEDIA_PLAY_PAUSE||k==KeyEvent.KEYCODE_MEDIA_PLAY||k==KeyEvent.KEYCODE_MEDIA_PAUSE){togglePlayback();return true;}if(k==KeyEvent.KEYCODE_MEDIA_REWIND){seekBy(-10000);return true;}if(k==KeyEvent.KEYCODE_MEDIA_FAST_FORWARD){seekBy(10000);return true;}if(getCurrentFocus()==seek&&k==KeyEvent.KEYCODE_DPAD_LEFT){seekBy(-10000);return true;}if(getCurrentFocus()==seek&&k==KeyEvent.KEYCODE_DPAD_RIGHT){seekBy(10000);return true;}}return super.dispatchKeyEvent(e);}
 void open(){buildSources();if(sources.isEmpty()){Toast.makeText(this,"Não foi possível reproduzir este conteúdo.",Toast.LENGTH_LONG).show();return;}
  player.addListener(new Player.Listener(){@Override public void onPlaybackStateChanged(int state){if(state==Player.STATE_READY){prepared=true;switching=false;bufferStarts=0;play.setText(player.isPlaying()?"Ⅱ":"▶");startTicker();updateProgressNow();}else if(state==Player.STATE_BUFFERING&&prepared&&!switching){long now=SystemClock.elapsedRealtime();bufferStarts=(now-lastBufferAt<30000)?bufferStarts+1:1;lastBufferAt=now;if(bufferStarts>=2)downgradeQuality();}else if(state==Player.STATE_ENDED){if(!live&&playNextEpisode())return;play.setText("▶");savePlaybackProgress(true);}}@Override public void onIsPlayingChanged(boolean isPlaying){if(play!=null)play.setText(isPlaying?"Ⅱ":"▶");}@Override public void onPlayerError(PlaybackException error){if(sourceIndex+1<sources.size()){downgradeQuality();return;}Toast.makeText(PlayerActivity.this,"Não foi possível reproduzir este conteúdo.",Toast.LENGTH_LONG).show();}});
  startSource(sourceIndex,pendingSeek);
 }
 void buildSources(){sources.clear();String def=null,q1080=null,q720=null,q480=null,q320=null;HashMap<String,String> ep=currentEpisode();if(ep!=null){def=ep.get("url");q1080=ep.get("url_1080");q720=ep.get("url_720");q480=ep.get("url_480");q320=ep.get("url_320");}else{def=getIntent().getStringExtra("url");q1080=getIntent().getStringExtra("url_1080");q720=getIntent().getStringExtra("url_720");q480=getIntent().getStringExtra("url_480");q320=getIntent().getStringExtra("url_320");}boolean cellular=isCellular();if(cellular){addSource(q720);addSource(q480);addSource(q320);addSource(q1080);}else{addSource(q1080);addSource(q720);addSource(q480);addSource(q320);}addSource(def);}
 HashMap<String,String> currentEpisode(){synchronized(PlayerActivity.class){if(!episodeQueue||episodeIndex<0||episodeIndex>=EPISODE_QUEUE.size())return null;return EPISODE_QUEUE.get(episodeIndex);}}
 boolean playNextEpisode(){savePlaybackProgress(true);synchronized(PlayerActivity.class){if(!episodeQueue||episodeIndex<0||episodeIndex+1>=EPISODE_QUEUE.size())return false;episodeIndex++;EPISODE_INDEX=episodeIndex;}applyEpisodeMetadata();sourceIndex=0;pendingSeek=0;bufferStarts=0;switching=false;prepared=false;buildSources();if(sources.isEmpty())return false;startSource(0,0);return true;}
 void applyEpisodeMetadata(){HashMap<String,String> ep=currentEpisode();if(ep==null)return;episodeId=nz(ep.get("id"));episodeTitle=nz(ep.get("title"));seasonNumber=nz(ep.get("season"));episodeNumber=nz(ep.get("episode"));}
 String resumeKey(){String provider=getSharedPreferences("gp",0).getString("provider_id","");return "series_resume_"+(provider+"_"+seriesId).replaceAll("[^a-zA-Z0-9._-]","_");}
 String movieResumeKey(){String provider=getSharedPreferences("gp",0).getString("provider_id","");return "movie_resume_"+(provider+"_"+movieId).replaceAll("[^a-zA-Z0-9._-]","_");}
 void savePlaybackProgress(boolean completed){if(live)return;int pos=safePosition();long dl=durationMs();int dur=dl>Integer.MAX_VALUE?Integer.MAX_VALUE:(int)Math.max(0,dl);android.content.SharedPreferences sp=getSharedPreferences("gp",0);if(!seriesId.isEmpty()&&!episodeId.isEmpty()){if(completed||(dur>0&&pos>=dur-3000)){sp.edit().remove(resumeKey()).apply();return;}if(pos<3000||dur<=0)return;try{org.json.JSONObject r=new org.json.JSONObject();r.put("episode_id",episodeId);r.put("episode_title",episodeTitle);r.put("season_number",seasonNumber);r.put("episode_number",episodeNumber);r.put("position",pos);r.put("duration",dur);r.put("updated_at",System.currentTimeMillis());sp.edit().putString(resumeKey(),r.toString()).apply();}catch(Exception ignored){}return;}if(movieId.isEmpty())return;if(completed||(dur>0&&pos>=dur-3000)){sp.edit().remove(movieResumeKey()).apply();return;}if(pos<3000||dur<=0)return;try{org.json.JSONObject r=new org.json.JSONObject();r.put("movie_id",movieId);r.put("movie_title",movieTitle);r.put("movie_poster",moviePoster);r.put("movie_landscape",movieLandscape);r.put("position",pos);r.put("duration",dur);r.put("updated_at",System.currentTimeMillis());sp.edit().putString(movieResumeKey(),r.toString()).apply();}catch(Exception ignored){}}
 void addSource(String u){if(u==null)return;u=u.trim();if(u.isEmpty()||sources.contains(u))return;sources.add(u);}
 boolean isCellular(){try{ConnectivityManager cm=(ConnectivityManager)getSystemService(Context.CONNECTIVITY_SERVICE);android.net.NetworkInfo ni=cm==null?null:cm.getActiveNetworkInfo();return ni!=null&&ni.isConnected()&&ni.getType()==ConnectivityManager.TYPE_MOBILE;}catch(Exception e){return false;}}
 Uri sourceUri(String u){if(u==null)return Uri.EMPTY;u=u.trim();if(u.startsWith("/"))return Uri.fromFile(new java.io.File(u));return Uri.parse(u);}
 void startSource(int idx,int seekMs){if(idx<0||idx>=sources.size()||player==null)return;sourceIndex=idx;pendingSeek=Math.max(0,seekMs);prepared=false;switching=false;String u=sources.get(idx);try{player.stop();player.clearMediaItems();player.setMediaItem(MediaItem.fromUri(sourceUri(u)));if(pendingSeek>0&&!live)player.seekTo(pendingSeek);pendingSeek=0;player.setPlayWhenReady(true);player.prepare();playerView.requestFocus();}catch(Exception e){if(sourceIndex+1<sources.size())downgradeQuality();else Toast.makeText(this,"Não foi possível reproduzir este conteúdo.",Toast.LENGTH_LONG).show();}}
 void downgradeQuality(){if(switching||sourceIndex+1>=sources.size())return;switching=true;int pos=live?0:safePosition();sourceIndex++;bufferStarts=0;h.postDelayed(()->startSource(sourceIndex,pos),120);}
 int safePosition(){long p=positionMs();return p>Integer.MAX_VALUE?Integer.MAX_VALUE:(int)p;}
 void updateProgressNow(){if(player==null||time==null||seek==null)return;long cur=positionMs(),dur=durationMs();time.setText(fmt(cur)+(live?"  •  AO VIVO":dur>0?" / "+fmt(dur):""));if(!live&&dur>0)seek.setProgress((int)Math.max(0,Math.min(1000,1000d*cur/dur)));}
 void startTicker(){if(tickerStarted)return;tickerStarted=true;h.postDelayed(new Runnable(){public void run(){if(isFinishing())return;if(player!=null&&prepared){if(!seekingTouch)updateProgressNow();if(!live&&(!seriesId.isEmpty()||!movieId.isEmpty())&&SystemClock.elapsedRealtime()-lastProgressSave>5000){lastProgressSave=SystemClock.elapsedRealtime();savePlaybackProgress(false);}}h.postDelayed(this,750);}},750);}
 String fmt(long ms){long total=Math.max(0,ms/1000),h=total/3600,m=(total%3600)/60,s=total%60;return h>0?String.format(java.util.Locale.US,"%d:%02d:%02d",h,m,s):String.format(java.util.Locale.US,"%02d:%02d",m,s);}
 @Override protected void onPause(){savePlaybackProgress(false);try{resumeAfterBackground=player!=null&&player.isPlaying();if(player!=null)player.pause();}catch(Exception ignored){}super.onPause();}
 @Override protected void onStop(){try{if(player!=null)player.pause();}catch(Exception ignored){}super.onStop();}
 @Override protected void onResume(){super.onResume();applyImmersive();if(resumeAfterBackground&&player!=null&&prepared){resumeAfterBackground=false;player.play();}}
 public void onDestroy(){savePlaybackProgress(false);releaseStreamSession();h.removeCallbacksAndMessages(null);try{if(player!=null){player.pause();player.release();player=null;}}catch(Exception ignored){}super.onDestroy();}
}
